### ISSUE TITLE
Missing files in the created project.

### ISSUE THREAD

**Issue by JCDubs** [pledbrook/lazybones#162]
I have created a lazybones template containing files in the root directory and sub directories. I have expanded the zip to make sure that all files have been included and the structure of the generated zip is as expected. The structure is similar to:

    Root
        -> bower.js
        -> grunt.js
        -> server.js
        -> app
            -> config
                -> config.js
        -> test
            -> e2e
               -> e2e.conf.js
            -> unit
                -> karma.conf.js

When I run `lazybones create <my package name> <my package version> <project directory path>`, lazybones executes, creates the project and outputs the readme file but the created project does not contain the sub directory files in the zip i.e.

     Root
        -> bower.js
        -> grunt.js
        -> server.js
        -> app
            -> config
                -> config.js(missing)
        -> test
            -> e2e
               -> e2e.conf.js(missing)
            -> unit
                -> karma.conf.js(missing)

The subdirectories are present but the contents are not. I have created the package based on the git hub instructions, the config is basic and minimal. The instructions do not state that I have to do anything extra to extract files located in subdirectories. Any help here would be greatly appreciated.

**Comment by pledbrook** [comment]
Could you make the package available somewhere for me to test? Thanks.

**Comment by JCDubs** [comment]
@pledbrook I have created a repository [here](https://github.com/JCDubs/lazybones-angular-grunt) and pushed the template for you to test, cheers.

**Comment by pledbrook** [comment]
This is working for me with Lazybones 0.8.1, although the files are different to the ones you describe above. What version of Lazybones are you using to install the package?

**Comment by JCDubs** [comment]
Im using lazybones 0.8.1 via GVM on Ubuntu 14.04

**Comment by pledbrook** [comment]
So to try to reproduce, I ran `./gradlew iAT` within the template project and then `lazybones create angular-grunt 1.0.0-SNAPSHOT ag-app`, which installed the template from the cache. This is on Mac OS X.

You could try running `lazybones --verbose ...` to see whether any useful information is displayed in the log output.

**Comment by JCDubs** [comment]
I will have a play, cheers @pledbrook
