### ISSUE TITLE
"No such property" error

### ISSUE THREAD

**Issue by saturov** [pledbrook/lazybones#171]
I have another strange issue. I added parameters to post-install script. 

This is fragment from my lazybones.groovy file.
```
def props = [projectName: projectDir.name]
props.shortname    	= ask('DEFAULT shortname ? [client]: ', 'client', 'shortname')
props.second    	  = ask('DEFAULT second ? [secondrule]: ', 'secondrule', 'second')
processTemplates 'build.gradle', props
processTemplates '**/strings.xml', props
```

The first parameter works perfeclty. Placeholder for it is placed in build.gradle file. But the second fails every time I try to generate project from the template! Placeholder for it is in strings.xml and it looks like:

`<string name="app_name">\${second}</string>`

I tried with or without this backslash but it doesn't matter at all. Everytime i have the same error message:

> Post install script caused an exception, project might be corrupt: No such property: Stub for class: SimpleTemplateScript2
> The unpacked template will remain in place to help you diagnose the problem

What am I doing wrong?

**Comment by pledbrook** [comment]
Is there a reference to `Stub` in any of the template files?

**Comment by saturov** [comment]
Actually, I don't know what is a Stub. Where can I read about it?

**Comment by saturov** [comment]
The problem was in "$" sign in parametrized string and in comment. Lazybones tried to set parameter to these places.

**Comment by saturov** [comment]
I think it's lazybones fault, if it recognize every "$" as param's start. But not just "${xxx}".

**Comment by pledbrook** [comment]
There's not much I can do about that. It's the way the Groovy template engine works. There is built-in support for Handlebars templates if you prefer those.

**Comment by raghava-joijode** [comment]
Hi, What could be solution for this. I am also facing same issue.
