### ISSUE TITLE
Proxy user authentication not working properly

### ISSUE THREAD

**Issue by ricardogobbo** [pledbrook/lazybones#172]
My computer is behind a proxy that uses authentication. I presume that a default autenticator isn't set. This code should be called after processSystemProperties in Configuration.

```
Authenticator.setDefault(new Authenticator() {
    @Override
    protected PasswordAuthentication getPasswordAuthentication() {
        if (getRequestorType() == RequestorType.PROXY) {
            String prot = getRequestingProtocol().toLowerCase();
            String host = System.getProperty(prot + ".proxyHost", "");
            String port = System.getProperty(prot + ".proxyPort", "80");
            String user = System.getProperty(prot + ".proxyUser", "");
            String password = System.getProperty(prot + ".proxyPassword", "");

            if (getRequestingHost().equalsIgnoreCase(host)) {
                if (Integer.parseInt(port) == getRequestingPort()) {
                    // Seems to be OK.
                    return new PasswordAuthentication(user, password.toCharArray());  
                }
            }
        }
        return null;
    }  
});
```

**Comment by pledbrook** [comment]
OK. I'll try to add this. I assumed that if you provided the system properties, it was all handled automatically. I guess that's not the case for challenge-based authentication.

**Comment by pledbrook** [comment]
I was unable to create a functional test to verify this behaviour, so do you mind testing a SNAPSHOT release? You can download it [from here](https://dl.dropboxusercontent.com/u/29802534/lazybones-0.8-SNAPSHOT.zip). If you're using sdkman, just unpack the distribution and then run

    sdk install lazybones dev <lazybones dir>

Please let me know if it works.

**Comment by ricardogobbo** [comment]
Hi Peter. Now it ran smoothly.
`http://prntscr.com/a7f6l9`

**Comment by pledbrook** [comment]
Thanks for letting me know. I'm working on a way to incorporate this scenario into the integration tests. Once I finish that, successfully or unsuccessfully, I'll publish a new version with the fix.
