### ISSUE TITLE
Create package on bintray with publishAllTemplates: VCS URL mandatory

### ISSUE THREAD

**Issue by madmas** [pledbrook/lazybones#174]
Hi,
I just wanted to publus a new lazybones template to bintray.

First, I upgraded to the latest plugin version which then complained

```
* What went wrong:
A problem occurred evaluating root project 'dolphin-platform-lazybones-templates'.
> No such property: vcsUrl for class: uk.co.cacoethes.gradle.lazybones.LazybonesConventions_Decorated
```

So I removed that property. 
But now, the Bintray API is not happy anymore are the VCS URL seems to be a mandatory field:

```
Checking if package [...] already exists
Creating package [...] via https://api.bintray.com/packages/[...]/[...] 
Failed to create package [...] . Response from Bintray:
{"message":"Please enter a valid VCS URL for your OSS package."}
```

I got around this by creating the package on the Bintray web UI first, but I think the plugin should reflect the VCS URL as being mandatory - or did I miss/oversee something ? :)

**Comment by pledbrook** [comment]
Seems like a duplicate of #154. Are you using the latest version of the plugin?

**Comment by pledbrook** [comment]
The property's definitely [there](https://github.com/pledbrook/lazybones/blob/master/lazybones-gradle-plugin/src/main/groovy/uk/co/cacoethes/gradle/lazybones/LazybonesConventions.groovy#L73). I'm hoping it's a version issue, because otherwise I'm stumped!

**Comment by madmas** [comment]
Hi,
I've had the impression that 1.2.3 is the most recent version of the plugin, but double-checking it revealed that 1.2.4 is the one - and with that, vcsUrl is working.
Hence, also publishing a non-existant package works as expected, sorry for the wrong alarm.
I created a PR to update the readme to the most recent version ;-) https://github.com/pledbrook/lazybones/pull/175

thank you :), I'm closing this as it seems to be solved.
